version: '3.8'

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ebsdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  scraper:
    build:
      context: ./scraper
    env_file:
      - ./scraper/.env
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/ebsdb
    depends_on:
      - db
    volumes:
      - ./scraper:/app
      - ./config.json:/app/config.json

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app"

volumes:
  pgdata:
